name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-lib:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build Lib
        run: npm run build:lib

      - name: Run Tests
        run: npm run cy:run:component

      - name: Extract Version
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        id: extract-version
        run: echo "::set-output name=version::$(jq -r '.version' projects/ngx-pmr-duration-picker/package.json)"

      - name: Check NPM version existence
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          VERSION_EXISTS=$(npm view ngx-pmr-duration-picker@${{ steps.extract-version.outputs.version }} --json || echo "{}")
          if [[ -z "$VERSION_EXISTS" ]]; then
            echo "Version does not exist on NPM registry."
          else
            echo "Version already exists on NPM registry."
            exit 0
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Artifact
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          cp README.md ./dist/ngx-pmr-duration-picker
          npm run publish:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Create Draft Release on GH
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract-version.outputs.version }}
          release_name: ${{ steps.extract-version.outputs.version }}
          draft: false
          prerelease: false
