name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build Lib
        run: npm run build:lib

      - name: Run Tests
        run: npm run cy:run:component

      - name: Check NPM version existence
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          VERSION=$(npm view ngx-pmr-duration-picker@$npm_package_version --json)
          if [[ -z "$VERSION" ]]; then
            echo "Version does not exist on NPM registry."
          else
            echo "Version already exists on NPM registry."
            exit 1
          fi

      - name: Publish Artifact
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run publish:lib
