name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  VERSION: $(jq -r '.version' projects/ngx-pmr-duration-picker/package.json)

jobs:
  build-lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build Lib
        run: npm run build:lib

      - name: Run Tests
        run: npm run cy:run:component

      - name: Check NPM version existence
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          VERSION_EXISTS=$(npm view ngx-pmr-duration-picker@${{env.VERSION}} --json || echo "{}")
          if [[ -z "$VERSION_EXISTS" ]]; then
            echo "Version does not exist on NPM registry."
          else
            echo "Version already exists on NPM registry."
            exit 0
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Artifact
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: npm run publish:lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Draft Release on GH
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.VERSION}}
          release_name: ${{env.VERSION}}
          draft: true
          prerelease: false
